version: '3.4'

services:
  mc2.crudtest.presentation.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Server=mssqlserver;Database=Sample;Persist Security Info=True;UID=sa;Password=Jahan*0021;MultipleActiveResultSets=True;TrustServerCertificate=True
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro